export const GET_ADMIN_INFO_REQ = "GET_ADMIN_INFO_REQ";
export const GET_ADMIN_INFO_SUCC = "GET_ADMIN_INFO_SUCC";
export const GET_ADMIN_INFO_FAIL = "GET_ADMIN_INFO_FAIL";

export const GET_ADMIN_CHART_REQ = "GET_ADMIN_CHART_REQ";
export const GET_ADMIN_CHART_SUCC = "GET_ADMIN_CHART_SUCC";
export const GET_ADMIN_CHART_FAIL = "GET_ADMIN_CHART_FAIL";
