export const PLACE_ORDER_REQ = "PLACE_ORDER_REQ";
export const PLACE_ORDER_SUCC = "PLACE_ORDER_SUCC";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";

export const GET_ORDER_REQ = "GET_ORDER_REQ";
export const GET_ORDER_SUCC = "GET_ORDER_SUCC";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_ALL_ORDERS_REQ = "GET_ALL_ORDERS_REQ";
export const GET_ALL_ORDERS_SUCC = "GET_ALL_ORDERS_SUCC";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const GET_DELIVERED_ORDERS_REQ = "GET_DELIVERED_ORDERS_REQ";
export const GET_DELIVERED_ORDERS_SUCC = "GET_DELIVERED_ORDERS_SUCC";
export const GET_DELIVERED_ORDERS_FAIL = "GET_DELIVERED_ORDERS_FAIL";

export const GET_NOTDELIVERED_ORDERS_REQ = "GET_NOTDELIVERED_ORDERS_REQ";
export const GET_NOTDELIVERED_ORDERS_SUCC = "GET_NOTDELIVERED_ORDERS_SUCC";
export const GET_NOTDELIVERED_ORDERS_FAIL = "GET_NOTDELIVERED_ORDERS_FAIL";

export const GET_ORDER_BY_ADMIN_REQ = "GET_ORDER_BY_ADMIN_REQ";
export const GET_ORDER_BY_ADMIN_SUCC = "GET_ORDER_BY_ADMIN_SUCC";
export const GET_ORDER_BY_ADMIN_FAIL = "GET_ORDER_BY_ADMIN_FAIL";

export const EDIT_ORDER_BY_ADMIN_REQ = "EDIT_ORDER_BY_ADMIN_REQ";
export const EDIT_ORDER_BY_ADMIN_SUCC = "EDIT_ORDER_BY_ADMIN_SUCC";
export const EDIT_ORDER_BY_ADMIN_FAIL = "EDIT_ORDER_BY_ADMIN_FAIL";
