export const GET_ALL_PRODUCTS_REQ = "GET_ALL_PRODUCTS_REQ";
export const GET_ALL_PRODUCTS_SUCC = "GET_ALL_PRODUCTS_SUCC";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const PRODUCT_VIEW_REQ = "PRODUCT_VIEW_REQ";
export const PRODUCT_VIEW_SUCC = "PRODUCT_VIEW_SUCC";
export const PRODUCT_VIEW_FAIL = "PRODUCT_VIEW_FAIL";

export const PRODUCT_REV_REQ = "PRODUCT_REV_REQ";
export const PRODUCT_REV_SUCC = "PRODUCT_REV_SUCC";
export const PRODUCT_REV_FAIL = "PRODUCT_REV_FAIL";

export const PRODUCT_CAT_REQ = "PRODUCT_CAT_REQ";
export const PRODUCT_CAT_SUCC = "PRODUCT_CAT_SUCC";
export const PRODUCT_CAT_FAIL = "PRODUCT_CAT_FAIL";

export const PRODUCT_CREATE_REQ = "PRODUCT_CREATE_REQ";
export const PRODUCT_CREATE_SUCC = "PRODUCT_CREATE_SUCC";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

export const PRODUCT_EDIT_REQ = "PRODUCT_EDIT_REQ";
export const PRODUCT_EDIT_SUCC = "PRODUCT_EDIT_SUCC";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";

export const PRODUCT_DEL_REQ = "PRODUCT_DEL_REQ";
export const PRODUCT_DEL_SUCC = "PRODUCT_DEL_SUCC";
export const PRODUCT_DEL_FAIL = "PRODUCT_DEL_FAIL";

export const CATEGORY_CREATE_REQ = "CATEGORY_CREATE_REQ";
export const CATEGORY_CREATE_SUCC = "CATEGORY_CREATE_SUCC";
export const CATEGORY_CREATE_FAIL = "CATEGORY_CREATE_FAIL";

export const CATEGORY_UPDATE_REQ = "CATEGORY_UPDATE_REQ";
export const CATEGORY_UPDATE_SUCC = "CATEGORY_UPDATE_SUCC";
export const CATEGORY_UPDATE_FAIL = "CATEGORY_UPDATE_FAIL";

export const CATEGORY_DELETE_REQ = "CATEGORY_DELETE_REQ";
export const CATEGORY_DELETE_SUCC = "CATEGORY_DELETE_SUCC";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
